const getSampleVocData = () => {
  const now = new Date();
  const yesterday = new Date(now);
  yesterday.setDate(now.getDate() - 1);
  
  const weekAgo = new Date(now);
  weekAgo.setDate(now.getDate() - 7);
  
  const nextWeek = new Date(now);
  nextWeek.setDate(now.getDate() + 7);
  
  return [
    {
      no: 1,
      regDate: weekAgo,
      vocCategory: 'MES 아산',
      requestDept: '생산팀',
      requester: '홍길동',
      systemPath: '생산관리 > 작업지시',
      request: '작업지시 화면에서 공정별 작업자 현황 조회 기능이 필요합니다.',
      requestType: '신규',
      action: '기능 개발 완료 및 테스트 진행 중',
      actionTeam: '개발1팀',
      actionPerson: '김개발',
      status: '진행중',
      dueDate: nextWeek,
    },
    {
      no: 2,
      regDate: new Date(weekAgo.getTime() + 86400000),
      vocCategory: 'QMS 아산',
      requestDept: '품질관리팀',
      requester: '김품질',
      systemPath: '품질관리 > 검사결과',
      request: '검사결과 입력 시 오류가 발생합니다.',
      requestType: '오류',
      action: '데이터 유효성 검사 로직 수정',
      actionTeam: '개발2팀',
      actionPerson: '이개발',
      status: '완료',
      dueDate: yesterday,
    },
    {
      no: 3,
      regDate: yesterday,
      vocCategory: '그룹웨어',
      requestDept: '인사팀',
      requester: '박인사',
      systemPath: '전자결재 > 휴가신청',
      request: '휴가신청 화면에 연차 잔여일수 표시 기능을 추가해주세요.',
      requestType: '수정',
      action: '화면 설계 검토 중',
      actionTeam: '개발3팀',
      actionPerson: '최개발',
      status: '접수',
      dueDate: new Date(nextWeek.getTime() + 86400000 * 3),
    },
    {
      no: 4,
      regDate: now,
      vocCategory: 'MES 비나',
      requestDept: '해외생산팀',
      requester: '정해외',
      systemPath: '재고관리 > 재고현황',
      request: '베트남 공장 재고현황 데이터가 정확하지 않습니다.',
      requestType: '오류',
      action: '데이터 동기화 프로세스 검토 중',
      actionTeam: '인프라팀',
      actionPerson: '강개발',
      status: '접수',
      dueDate: new Date(nextWeek.getTime() + 86400000 * 5),
    },
    {
      no: 5,
      regDate: new Date(weekAgo.getTime() + 86400000 * 3),
      vocCategory: '하드웨어',
      requestDept: 'IT지원팀',
      requester: '오지원',
      systemPath: '네트워크 장비',
      request: '공장동 무선네트워크 접속 불안정 문제가 있습니다.',
      requestType: '문의',
      action: '현장 점검 완료, AP 교체 작업 진행 예정',
      actionTeam: '인프라팀',
      actionPerson: '우개발',
      status: '진행중',
      dueDate: new Date(now.getTime() + 86400000 * 2),
    },
    {
      no: 6,
      regDate: new Date(now.getTime() - 86400000 * 4),
      vocCategory: 'QMS 비나',
      requestDept: '해외품질팀',
      requester: '한품질',
      systemPath: '품질관리 > 불량현황',
      request: '비나 공장 불량유형 코드를 추가해주세요.',
      requestType: '신규',
      action: '코드 추가 완료',
      actionTeam: '개발2팀',
      actionPerson: '양개발',
      status: '완료',
      dueDate: new Date(yesterday.getTime() - 86400000),
    },
    {
      no: 7,
      regDate: new Date(now.getTime() - 86400000 * 3),
      vocCategory: '소프트웨어',
      requestDept: '경영지원팀',
      requester: '조경영',
      systemPath: 'Office > Excel',
      request: 'Excel 매크로 작동 오류가 있습니다.',
      requestType: '오류',
      action: '보안 정책으로 인한 문제, 보안 설정 변경 필요함을 안내',
      actionTeam: 'IT지원팀',
      actionPerson: '배개발',
      status: '완료',
      dueDate: new Date(now.getTime() - 86400000),
    },
    {
      no: 8,
      regDate: new Date(now.getTime() - 86400000 * 5),
      vocCategory: '통신',
      requestDept: '영업팀',
      requester: '권영업',
      systemPath: 'VPN',
      request: '외부에서 VPN 접속이 안됩니다.',
      requestType: '오류',
      action: '고객사 방화벽 이슈 확인, 협의 필요',
      actionTeam: '인프라팀',
      actionPerson: '방개발',
      status: '보류',
      dueDate: nextWeek,
    },
    {
      no: 9,
      regDate: weekAgo,
      vocCategory: 'MES 아산',
      requestDept: '자재팀',
      requester: '임자재',
      systemPath: '자재관리 > 입고현황',
      request: '특정 자재코드 입고 내역이 조회되지 않습니다.',
      requestType: '오류',
      action: '데이터 쿼리 오류 수정',
      actionTeam: '개발1팀',
      actionPerson: '태개발',
      status: '완료',
      dueDate: new Date(yesterday.getTime() - 86400000 * 2),
    },
    {
      no: 10,
      regDate: new Date(now.getTime() - 86400000 * 2),
      vocCategory: '기타',
      requestDept: '총무팀',
      requester: '신총무',
      systemPath: '사내포털 > 공지사항',
      request: '공지사항에 첨부파일 다운로드가 안됩니다.',
      requestType: '오류',
      action: '파일 서버 연결 오류 확인 중',
      actionTeam: '개발3팀',
      actionPerson: '손개발',
      status: '진행중',
      dueDate: new Date(nextWeek.getTime() - 86400000),
    },
  ];
};

module.exports = { getSampleVocData }; 